pipeline {
    agent any
    tools {
           maven 'M3'
    }
    stages {
        stage('Build') {
            steps {
                script {
                    if (fileExists('?/.m2/repository/fr')) {
                        sh 'rm -r ?/.m2/repository/fr'
                    }
                }

                sh 'mvn clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Deploy') {
            steps {
                sh 'mvn clean install'
            }
        }
    }
}